### ISSUE TITLE
isort found an import in the wrong position

### ISSUE THREAD

**Issue by Bazulenkov** [gforcada/flake8-isort#100]
I use black as formatter.

flake8-isort give me a problem with this code:
```
from rest_framework import status
from rest_framework.parsers import JSONParser
from rest_framework.response import Response
from rest_framework.views import APIView

from kvolos.api.exceptions import CustomError
from logic.managers.ordermanager import OrderManager

from ..apiviews import BaseOrderView
from .serializers import (
    ExtUuidOrderSerializer,
    OrderIdsSerializer,
    OrderSerializer,
    PositionCreateSerializer,
    PositionSerializer,
    ProductSerializer,
    ProfileIdSerializer,
)
```
![Screenshot from 2021-07-29 14-32-31](https://user-images.githubusercontent.com/38315253/127485139-58a4533a-bd99-4427-8544-c65e68d626aa.png)

**Comment by gforcada** [comment]
hi @Bazulenkov ! thanks for using, and reporting your usage of flake8-isort! 🎉 

To be able to debug your problem, would you mind giving the versions you are using? for at least python, isort, flake8 and flake8-isort

**Comment by Bazulenkov** [comment]
flake8 --version
`3.9.2 (flake8_isort: 4.0.0, mccabe: 0.6.1, pycodestyle: 2.7.0, pyflakes: 2.3.1) CPython 3.8.10 on Linux`
isort - verison 5.8.0
Python 3.8.10

**Comment by gforcada** [comment]
sorry for the long delay on my answer... 😓 if I install the version you told me and without any specific isort configuration, I got them formatted quite different. You might try to run `isort file.py` and see how isort is actually formatting it. `isort` is highly configurable, you might want to first look at how you want your imports to look like there and then save the configuration on the root folder of your project.

If you already have done that, then, please share that configuration, otherwise I can not debug it.

Sorry again for my delay on the answer.

**Comment by madpenguinw** [comment]
Hello! I faced the same problem.
The imports must be arranged in alphabetical order.

**Comment by 71andy** [comment]
I faced the same problem.
You should use isort option:
`multi_line_output = 3`
see https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#isort
