### ISSUE TITLE
New release - testfixtures 7.x

### ISSUE THREAD

**Issue by g-as** [gforcada/flake8-isort#114]
Hi,

`testfixtures` 7 is out, but cannot be updated along with `4.1.1`.

Releasing `4.1.2` would be great.

Cheers

**Comment by gforcada** [comment]
Hi @g-as thanks for using and reporting your findings with `flake8-isort` ! 😃 

I see that the `master` branch no longer depends on `testfixtures` anymore, so a new release would solve the problem indeed.

Unfortunately I'm on vacations now, but expect a release around next week, otherwise, please a friendly ping is always welcomed, as I'm rather busy at work (and specially after vacations) so I might forget about it 👍🏾

**Comment by g-as** [comment]
Hahahahaha alright.

Enjoy!

**Comment by gforcada** [comment]
Release done: 4.1.2.post0 (the `post0` is because I forgot to create a wheel 😓 )

**Comment by g-as** [comment]
thx
