### ISSUE TITLE
Incorrect version number

### ISSUE THREAD

**Issue by lukasbindreiter** [gforcada/flake8-isort#123]
Just encountered a weird issue:

```bash
> pip freeze | grep flake8-isort
flake8-isort==5.0.0
```

but flakeheaven tells me something different:
```bash
> flakeheaven plugins

NAME                         | VERSION  | CODES               | RULES
...
flake8-isort                 | 4.2.1    | I00                 | +*
...
```

I think this is because `4.2.1` is set here as version string: https://github.com/gforcada/flake8-isort/blob/master/flake8_isort.py#L12
Even though there is no such version released on pypi, could you maybe double check?

**Comment by gforcada** [comment]
@lukasbindreiter indeed, thanks for noticing!

(I think) that some time ago `flake8` started using the version of the plugin itself (the pypi package version I mean) rather than this internal version, so I stopped updating it. I can try to see if deleting it makes it work.

If you have the time to test that yourself, _please be my guest_ 😄 otherwise ping me in a few days if I haven't said anything, I'm rather busy with life, family and work 😓

**Comment by gforcada** [comment]
A new release is out `flake8-isort==5.0.1` with a fixed version number 😄

**Comment by lukasbindreiter** [comment]
Thank you very much :smile:

**Comment by lukasbindreiter** [comment]
I think you forgot to update the version number again for the following releases (`5.0.2` and `5.0.3`).

(It's not really that urgent and not blocking me in any ways, just wanted to let you know :smile: )

**Comment by lukasbindreiter** [comment]
Theoretically it could be replaced by something like:

```python
from pkg_resources import get_distribution

version = get_distribution("flake8_isort").version
```

but that has some runtime cost attached, not sure if that is wanted

**Comment by gforcada** [comment]
yeah right, PRs welcome 😉

**Comment by gforcada** [comment]
I think `flake8` is slow enough to not be too much to get a package version 😅

**Comment by lukasbindreiter** [comment]
> yeah right, PRs welcome 😉

#129
